name: publish site
on: # 在什么时候触发工作流
  push: # 在从分支被push到GitHub仓库时
    branches:
      - master
      - main
  pull_request: # 在分支合并别人提的pr时
    branches:
      - master
      - main
jobs: # 工作流的具体内容
  deploy:
    runs-on: ubuntu-latest # 创建一个新的云端虚拟机 使用最新Ubuntu系统
    steps:
      - uses: actions/checkout@v2 # 获得仓库代码
      - uses: actions/setup-python@v2 # 安装Python
        with:
          python-version: 3.x
      - run: pip install jieba
      - run: pip install mkdocs-material # 使用pip包管理工具安装mkdocs-material
      - run: mkdocs gh-deploy --force # 使用mkdocs-material部署gh-pages分支